import { StyleSheet } from 'react-native';
import { COLORS } from '../../utils/Constants';

const styles = StyleSheet.create({
  topUI: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: COLORS.UI_BACKGROUND + 'F0',
    borderBottomWidth: 2,
    borderBottomColor: COLORS.UI_BORDER,
    zIndex: 10,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  statItem: {
    alignItems: 'center',
    minWidth: 80,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.TEXT_SECONDARY,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    color: COLORS.TEXT,
    fontWeight: 'bold',
  },
  comboText: {
    color: COLORS.WARNING,
    fontSize: 20,
  },
  enemyHealthContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.UI_BORDER,
  },
  enemyHealthItem: {
    alignItems: 'center',
    flex: 1,
  },
  enemyLabel: {
    fontSize: 10,
    color: COLORS.TEXT_SECONDARY,
    marginBottom: 4,
  },
  enemyHealthBar: {
    width: 80,
    height: 4,
    backgroundColor: COLORS.UI_BORDER,
    borderRadius: 2,
    overflow: 'hidden',
  },
  enemyHealthFill: {
    height: '100%',
    borderRadius: 2,
  },
  container: {
    flex: 1,
  },
  resultMessageContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -150 }, { translateY: -20 }],
    width: 300,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(0,0,0,0.8)',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  resultMessageText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  healthBar: {
    width: 100,
    height: 8,
    backgroundColor: COLORS.UI_BORDER,
    borderRadius: 4,
    marginVertical: 4,
    overflow: 'hidden',
  },
  healthFill: {
    height: '100%',
    borderRadius: 4,
  },
  bottomUI: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: COLORS.UI_BACKGROUND + 'F0',
    borderTopWidth: 2,
    borderTopColor: COLORS.UI_BORDER,
    zIndex: 10,
  },
  controlsContainer: {
    alignItems: 'center',
  },
  actionIndicator: {
    marginBottom: 10,
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: COLORS.UI_BACKGROUND,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY,
  },
  actionText: {
    fontSize: 16,
    color: COLORS.TEXT,
    fontWeight: 'bold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
  },
  buttonWrapper: {
    alignItems: 'center',
  },
  buttonLabel: {
    fontSize: 12,
    color: COLORS.TEXT_SECONDARY,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
    fontWeight: '600',
  },
  buttonDescription: {
    fontSize: 10,
    color: COLORS.TEXT_SECONDARY,
    marginBottom: 2,
  },
  centerSpace: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
  },
  gameStateText: {
    fontSize: 16,
    color: COLORS.PRIMARY,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
});

export default styles;
